on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash
    working-directory: github_event_receiver_lambda

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage

      - name: Lint with flake8
        run: flake8 . --count --max-complexity=12 --max-line-length=127 --statistics --exclude venv

      - name: Test with pytest
        run: coverage run -m pytest

      - name: Check coverage
        working-directory: src
        run: coverage report --fail-under=80